transferwise/styleguide-components

angular/components/tw-upload-droppable/tw-upload-droppable.directive.js
If there is no title set on the droppable and the consumer wants to convey info using the transclusion then the m-t-2 spacing makes the content look odd.
=> Remove spacing between <i> and transcluded elements

angular/components/tw-amount-currency-select/tw-amount-currency-select.directive.js, index.html, partials/tw-amount-currency-select.html
I couldn't really find a way to test it from here as `tw-number-input-formatter` is not present it doesn't format anyway.
But it follows the same logic used in tw-currency-input so I expect it to be ok.
If you have any idea to test, let me know :) (like is it possible to import it in another project without having it released?)
=> Add show-decimals option to tw-amount-currency-select

dist/js/styleguide-components.js, package.json, src/forms/upload/upload.component.js, src/forms/upload/upload.controller.js, src/forms/upload/upload.html
**Changes:**
- Fixed small cosmetic issue the extra `quote mark` in the end of the template (upload.html),
- added `ngDisabled` handling to dropDown (drag and drop) component, input and label elements,
- added dist directory (built) files,
- bumped minor version (package.json),
**Questions:**
- upload.controller.js is the code changed good there?
- `npm test `now is failing
Tested locally and manually UI test and worked fine in every case.
(disabled, not disabled, later changing the disabled flag)
`Failing tests has no relation to these changes, but still concerning (maybe because of different locale settings
`
```
FAILED TESTS:
DateFormat filter,
Given the locale is en-GB
and a short format is requested
✖ should shorten the formatted value
PhantomJS 2.1.1 (Mac OS X 0.0.0)
Expected '5th …
```
=> Tw upload changes

CHANGELOG.md, package-lock.json, package.json, src/forms/definition-list/definition-list.html
=> Add text-word-break to Descripton List elements to avoid overflow

CHANGELOG.md, package.json, src/forms/form-control/form-control.html, src/forms/form-control/form-control.spec.js
Remove the upload switch case from form-control since it is redundant.
Looking at the getControlType logic in https://github.com/transferwise/styleguide-components/blob/master/src/services/requirements/requirements.service.js#L379 that is used by the field component, 'upload' is never returned and so the field component will never pass down 'upload' type to form-control, making it redundant.
=> remove redundant upload switch case from form-control

CHANGELOG.md, package-lock.json, package.json, src/layout/cards/card.html
We have been using button styles so hovering over chevrons presents a wrong behaviour. This PR should fix it.
=> [EXP-XXX] Fix styles for chevrons on cards

CHANGELOG.md, package.json, src/forms/field/field.component.js, src/forms/field/field.controller.js, src/forms/field/field.demo.html, src/forms/field/field.demo.js, src/forms/field/field.html, src/forms/field/field.spec.js, src/forms/fieldset/fieldset.html, src/forms/fieldset/fieldset.spec.js, src/services/requirements/requirements.service.js, src/services/requirements/requirements.spec.js
helpText, helpList & helpImage are now expected to be nested as 
```
help: {
message: "...",
list: [...],
image: "..."
}
```
Required is now supplied as per JSON schema spec so as an array on the object
```
{
type: "object",
required: ["name"],
properties: {
name: { type: "string" }
}
}
```
Not as a boolean within the property
```
{
type: "object",
properties: {
name: { type: "string", required: true }
}
}
```
twField therefore adds a property 'required' as the data is no longer within the 'field' data.
```
<tw-field field="$ctrl.field" required="true"></tw-field>
```
=> Change requirements help format & align with JSON schema for 'required'

CHANGELOG.md, package.json, src/forms/upload/upload.html
When `cancelText` is not provided to the upload component: the user has no way to change the file they uploaded.
**Current UI, with `cancelText` _(this behavior will remain the same)_:**
**Updated UI, with missing `cancelText`:**
=> fix(upload): Unable to remove file if cancelText is not provided [USD-3124]

CHANGELOG.md, package.json, src/forms/select/select.controller.js, src/forms/select/select.demo.js, src/forms/select/select.html, src/forms/select/select.spec.js
We were informed that the UI would freeze when someone was trying to add a Japanese recipient for a to-JPY transfer: https://transferwise.slack.com/archives/C0JNUL7RD/p1558104250003800. It turns out Japan would generate the largest amount of entries for bank or branch codes (over 3000). There are multiple things that can be improved but one of them was that `tw-select` would create 3000 elements on the page.
This PR improves `tw-select` for when there's such a high number of options. Specifically, it will only render the first 50 entries, with a `...` at the bottom. Click it and the list expands to 100. Click it again and the list expands to 150 etc. The `...` doesn't appear if there's less than 51 options.
=> ASIA-2103: Improve tw-select performance when it has a large number of options

CHANGELOG.md, package-lock.json, package.json, src/forms/select/select.controller.js, src/forms/select/select.spec.js
Increasing tw-select large option size from 50 to 300. It caused problems with frontend-apps protractor tests. 
Thread: https://transferwise.slack.com/archives/CK8HAK6DA/p1560934456004000
=> Increase tw-select large option size from 50 to 300

CHANGELOG.md, package-lock.json, package.json, src/forms/select/select.controller.js, src/forms/select/select.spec.js
Comparing and eliminating duplicates in `twSelect` using only labels breaks most of the recipient dropdowns.
You can have several different recipients/bank account details using the same name - for example I can have 1000 recipients called `John Doe` but the current implementation would just allow me to render one in the available options.
This PR fixes that checking the values as well for the same label.
=> fix(select): filter duplicates based on label and value

.circleci/config.yml
Use LTS version of Node instead of 10.6 which has been released mid 2018.
=> chore: use LTS version of Node

CHANGELOG.md, package-lock.json, package.json, src/forms/fieldset/fieldset.controller.js
Fix unwanted `min` and `max` validation rules visibility.
- `error-min` and `error-max` CSS rule should hide the `The value is too low` and `The value is too high`error messages
- These CSS classes are generated in the DOM by reading an object key's like `error-{{ validationType }}` (where `validationType` is the key of the object)
- That object had wrong keys: `minimum` instead of `min` and `maximum` instead of `max`
- CSS classes were not matched, thus error message has been visible beside the fact that validation passed for these rules.
For some reason when a field validation has happened the `min` and `max` validation rules have been triggered automatically, however most of the times the field had no configuration for those validation properties.
After an investigation I've manage to …
=> fix(fieldset): use proper keys for matching CSS rule for hiding error message

CHANGELOG.md, package-lock.json, package.json, src/forms/select/select.controller.js, src/forms/select/select.spec.js
Only the first header option was displayed due to a bug in the logic determining the filtered options.
The logic did not handle properly those option objects which have no label and value but only have `header` key.
This should now be fixed with this PR.
=> fix(select): display all headers passed to options

CHANGELOG.md, package-lock.json, package.json, src/forms/upload/camera-capture/camera-capture.less
We have an agreement with Steve to keep css for this component here for now while we are iterating on it. 
Current
Fixed
=> Camera upload component minor css fix

CHANGELOG.md, package-lock.json, package.json, src/forms/select/select.controller.js
This PR fixes the scenario when the `filteredOptions` is undefined in `twSelect` resulting in a `TypeError`.
=> fix: check if argument is an array before calling forEach on it

CHANGELOG.md, package-lock.json, package.json, src/forms/upload/upload.controller.js, src/forms/upload/upload.spec.js
Temporarily disable, via comments, functionality attached to the httpOptions binding used in tw-upload. This functionality shouldn't be used anywhere in production yet, however when used, it causes issues regarding base url and blocks a user from continuing to submit.
Until an appropriate solution is found, we will have it commented out, not block work on backend and other clients.
=> AT-901 Temporarily remove httpOptions funcationality

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, package-lock.json, package.json, src/forms/field/field.html, src/forms/fieldset/fieldset.html, src/forms/form-control/form-control.html, src/forms/upload/upload.component.js, src/forms/upload/upload.html, src/forms/upload/upload.spec.js
To be able to add copy to show during the processing stage on the upload component. Currently it is set up to accept multiple states (processing/success/failure), we want it to also be able to accept a constant state, because the success and failure screens follow.
`uploadOptions` was being propagated correctly through props. As fieldset was looking for it in the mitigator response. It doesn't exist there, instead it is supplied by parent components.
Add new key to `uploadOptions` - `uploadingText`. Fix prop binding for `uploadOptions`.
`btn-block`class is not needed and has been removed because it causes unwanted conflicting styles.
=> AT-932 add optional upload text

CHANGELOG.md, package-lock.json, package.json, src/forms/fieldset/fieldset.component.js, src/forms/fieldset/fieldset.html, src/forms/fieldset/fieldset.less
Before the fieldset used to have a class of btn-block (https://github.com/transferwise/styleguide-components/pull/266/files#diff-d07448f4be0dc1f1b6d4e37ce53fd3b0L53) when this was removed the fieldset was no longer 100%, see screenshots below. Hence adding 100% width to fix this. 
Adding width: 100%  and flex:1 to fieldset to get full-width
=> fix fieldset input width

CHANGELOG.md, package-lock.json, package.json, src/forms/upload/async-file-saver.service.js
When sending file via httpOptions, param key should come from httpOptions falling back to fieldName
Above.
=> At-NaN fix persist async file key

CHANGELOG.md, package-lock.json, package.json, src/forms/upload/upload.controller.js
Due to interceptors that live in frontend common. Error responses can be transformed. We need to check if they are and get the appropriate data if so.
Add additional conditional check for `originalData`
=> AT-969 fix reading failed res

CHANGELOG.md, package-lock.json, package.json, src/forms/upload/upload.html
Success headline was h4
Error headline was h5
now both are h5
fail icon was hidden on MD, SM, XS screens, now showing on all, same ass success icon
=> Fix: made success and error consistant

CHANGELOG.md, package-lock.json, package.json, src/forms/upload/upload.html, src/forms/upload/upload.less
To align CTAs on upload component when asking users to reupload.
Adds min-height to text to cater for certain size messages
=> Fix spacing on persistAsync feedback

CHANGELOG.md, package-lock.json, package.json, src/forms/upload/upload.html
Only hiding icons on success and error on XS screens
=> removed hide-sm on icons

CHANGELOG.md, package-lock.json, package.json, src/forms/upload/upload.controller.js, src/forms/upload/upload.spec.js
If an async action with upload, example persistAsync, fails. We don't want to halt the original flow or submitting the dataUrl. Only if the async action fails with a 422 with information to display to user, should be continue with the async action flow.
Check error response for status code and continue as normal if not 422.
=> AT-1097 Fix async action failure

CHANGELOG.md, package-lock.json, package.json, src/forms/upload/processing-card/index.js, src/forms/upload/processing-card/processing-card.html, src/forms/upload/upload.spec.js, src/loading/process/process.controller.js
Single file upload was not triggering a processing start initially outside of the demo. The user would have to click on the upload button again after selecting a file to trigger the process to start.
- Always render `tw-process` component in the single file upload
- call `onStateChange` initially to begin the interval to check for state change
=> Single file upload fix

CHANGELOG.md, package-lock.json, package.json, src/forms/upload/multi-upload/multi-upload.controller.js, src/forms/upload/multi-upload/multi-upload.spec.js, src/forms/upload/processing-card/processing-card.controller.js, src/forms/upload/upload.spec.js
When we use persistAsync and the service returns a non 422 error, we should treat it as an error in the component instead of succeeding.
Treat any error status codes as errors in the upload components
This will break the existing behaviour of ID checking since if the image upload fails with a 422, the user will not be able to carry on with the flow. This has been discussed and will only affect a small percentage of users
=> Remove 422 only failures for upload components

CHANGELOG.md, package-lock.json, package.json, src/forms/upload/multi-upload/multi-upload.component.js, src/forms/upload/multi-upload/multi-upload.controller.js, src/forms/upload/multi-upload/multi-upload.demo.html, src/forms/upload/multi-upload/multi-upload.demo.js, src/forms/upload/multi-upload/multi-upload.html, src/forms/upload/multi-upload/multi-upload.spec.js, src/forms/upload/processing-card/processing-card.controller.js, src/forms/upload/processing-card/processing-mini.html, src/forms/upload/upload.demo.js
Currently we only show the "failure-text" property if the upload fails. This is too vague.
- Display the `tooLargeMessage` passed in by the consumer if the file is too large
- Provides an onFailure callback which exposes the error. an error message can be extracted and passed as failure-text back to the component
- Rename "secondaryButtonText" to "addMoreButtonText"
Failure due to file size:
Failure due to server error:
Failure where client can't extract error message from server:
=> Display errors which are returned from persistAsync for multi file upload

CHANGELOG.md, package-lock.json, package.json, src/forms/upload/multi-upload/multi-upload.component.js, src/forms/upload/multi-upload/multi-upload.demo.html, src/forms/upload/multi-upload/multi-upload.demo.js, src/forms/upload/multi-upload/multi-upload.html, src/forms/upload/multi-upload/multi-upload.spec.js, src/forms/upload/processing-card/processing-card.controller.js, src/forms/upload/processing-card/processing.bindings.js
We want to display errors per file. The onFailure handler only modifies the root failureText which would change all error messages.
Provides a responseErrorExtractor which is called when a file fails to upload. This function is passed the error object in which the message can be extracted and returned. The resulting error message is then assigned to `$ctrl.errorMessage` in `processing-card.controller.js`.
=> add responseErrorExtractor callback for error message extraction

CHANGELOG.md, package-lock.json, package.json, src/forms/select/select.component.js, src/forms/select/select.controller.js
When a `twSelect` component is rendered with a valid `ngModel` and the `ngRequired` binding is set to `true` the parent component of `twSelect` did not got updated.
When a valid `ngModel` is present and `ngRequired` is set to true, the `twSelect` component should set the `ngModel` to the first option from the provided options which has a valid `value` property. This was already working, but the parent component of `twSelect` was not notified about this manual configuration step in `twSelect`.
`setDefaultIfRequired` implementation modified. This method now calls `$ctrl.ngChange` binding manually, wrapped into a `$timeout`.
=> fix(twSelect): manually trigger ngChange when option is manually set

CHANGELOG.md, package-lock.json, package.json, src/demo.js, src/formatting/demo.html, src/formatting/demo.js, src/formatting/index.js, src/formatting/markdown/index.js, src/formatting/markdown/markdown.component.js, src/formatting/markdown/markdown.controller.js, src/formatting/markdown/markdown.demo.html, src/formatting/markdown/markdown.demo.js, src/formatting/markdown/markdown.html, src/formatting/markdown/markdown.spec.js
For EDD source of funds question we want to display two bullet pointed lists to the user. This currently isn't possible so a markdown component is needed
introduces a markdown component
- still need to confirm mobile capacity for markdown implementation in v2.
- need to confirm which markdown features will be allowed in v3.
=> Markdown component

CHANGELOG.md, README.md, package-lock.json, package.json
Because when you run `npm test` on Ubuntu 16.04, you may get complaints about a bunch of missing dependencies. Most of them can be resolved by `apt install`, 1 can't and you'll have to manually compile it.
Updates the readme.
Consider how glad I am to be able to run tests now.
\-
=> Leave notes in the readme for testing when on Ubuntu 16.04

CHANGELOG.md, package-lock.json, package.json, src/forms/field/field.controller.js, src/forms/field/field.spec.js, src/forms/upload/upload.controller.js, src/forms/upload/upload.html, src/forms/upload/upload.less
When upload component is used with persistAsync. The API returns error messaging, with a message and validation messages. These however were not being shown at all within the component.
- Correctly passes up the error to the field component. 
- Check for `originalData` first as both `originalData` and `data` can exist where `data` is an object of various functions created by the http interceptor.
- Changes styling of processing card to allow wider content area to accommodate for validation messages
- Limits validation messages to two to avoid overspilling content.
=> AT-1340 Fix async validation messages

CHANGELOG.md, package-lock.json, package.json, src/forms/upload/camera-capture/camera-capture.html
Fixes a bug discovered with the recently refactored camera component introduced in https://github.com/transferwise/styleguide-components/pull/293 (v5.5.0).
Fix the width expression in `ng-style` attributes on the camera sub-components, so that they'll calculate validly.
This bug doesn't occur when running styleguide-components locally, but for whatever environmental reason, it won't work in `standalone-verification-app` unless the `+ 'px'` units are added. `+ ''` didn't work either, so it's not a numbers-vs-strings thing.
=> Fix ng-style widths not working sometimes

CHANGELOG.md, package-lock.json, package.json, src/forms/upload/camera-capture/camera-capture.controller.js
_(not guaranteed to fix anything, but it's a very cheap change, and it affects only Japan verification at this moment)_
Japan verification (the only users of the live camera component at the moment) have this very weird occasional JPG artifacting/corruption issue with users, where the JPGs uploaded will be split into 4 or 8 disjoint layers, with a discoloured band at the bottom (examples viewable in the ticket, if you have verification file access). This issue seems to have surfaced after https://github.com/transferwise/styleguide-components/pull/293/files.
Something in the capture pipeline is definitely broken, but we're not sure what (we can't reproduce it). But we've observed that so far all the broken images are 2300x2300px (which is the size we optionally request for (we arbitrarily …
=> ASIA-3207: Try changing the requested width/height of webcam requests

CHANGELOG.md, package-lock.json, package.json, src/forms/form-control/form-control.html, src/forms/upload/camera-capture/camera-capture.component.js, src/forms/upload/camera-capture/camera-capture.controller.js, src/forms/upload/camera-capture/camera-capture.spec.js, src/forms/upload/capture-card/capture-card.component.js, src/forms/upload/capture-card/capture-card.controller.js, src/forms/upload/capture-card/capture-card.html, src/forms/upload/upload.component.js, src/forms/upload/upload.demo.html, src/forms/upload/upload.demo.js, src/forms/upload/upload.html
When trying to invoke the live camera for Japan verification, the camera currently doesn't handle the error of the camera being unavailable (due to permissions issues etc.). As such it currently freezes on its translucent black loading screen.
This PR adds error messaging in the event of an inaccessible-camera case. The messages will be passed in externally by consumers (e.g. for Dynamic Forms, the 2 new messages will be passed in through `upload-options`).
A bit of discussion: https://transferwise.slack.com/archives/C2SGDKP4Y/p1587966855264000?thread_ts=1587966855.264000
Nil
=> Implement camera-permissions error messaging

CHANGELOG.md, package-lock.json, package.json, src/forms/upload/camera-button/camera-button.html, src/forms/upload/capture-card/capture-card.controller.js
It's a bit weird that the default icon for a camera-capture component is the upload icon, when uploading from disk is impossible.
Change the camera-capture component to show camera icons instead of upload icons.
If the user wants to override the helper icon and button text, they still can. This just changes the default that's shown if the user didn't do any overriding.
Did an eyeball check that non-camera uploads remain unaffected, and continue to show an upload icon by default:
=> ASIA-3209: Default to a camera icon instead of an upload icon for the camera upload component

CHANGELOG.md, package-lock.json, package.json, src/forms/telephone/countries.json, src/services/locale/locale.spec.js
https://transferwise.atlassian.net/browse/SEND-737
When creating a profile in the transferFlow we pass in the users locale to twTelephone based on the country they registered with. In the case of Australia, this is `en-AU`, which currently prefills the telephone input with `+672` - the phone code for Antarctica. 
This is because it's getting multiple hits for the `AU` `iso2` lookup it's doing in `countries.json`, and it is (for whatever reason) preferring whichever phone code is longer https://github.com/transferwise/styleguide-components/blob/master/src/forms/telephone/telephone.controller.js#L143-L149
Updates the Australian External Territories entry in `countries.json` to use the Antarctica iso2 code, supported by this note in Wikipedia on Australias external territories …
=> Update Australian External Territories entry in telephone countries

CHANGELOG.md, package.json, src/forms/checkbox-group/checkbox-group.component.js, src/forms/checkbox-group/checkbox-group.controller.js, src/forms/checkbox-group/checkbox-group.demo.html, src/forms/checkbox-group/checkbox-group.demo.js, src/forms/checkbox-group/checkbox-group.html, src/forms/checkbox-group/checkbox-group.spec.js, src/forms/definition-list/definition-list.controller.js, src/forms/definition-list/definition-list.html, src/forms/definition-list/definition-list.spec.js, src/forms/fieldset/fieldset.controller.js, src/forms/fieldset/fieldset.demo.js, src/forms/fieldset/fieldset.spec.js, src/forms/form-control/form-control.spec.js, src/forms/select/select.demo.html, src/services/requirements/requirements.service.js, src/services/requirements/requirements.spec.js, src/validation/control-validation/control-validation.controller.js
Sometimes when we do a refresh of the form, we end up with different fields, in that case we should remove any properties from the model that no longer appear in the set of fields
Alongside those changes we also improve the checkbox-group implementation to work with numeric enums as well as strings.  The requirements service now better identifies checkbox-groups based on their data type, and we have improved the definition list to show the labels for the enums rather than the raw values.
=> Make Fieldset remove invalid properties when it receives new fields

CHANGELOG.md, package.json, src/forms/fieldset/fieldset.controller.js, src/forms/fieldset/fieldset.spec.js
The verification-components consumer was propagating the onRefreshRequirements callback and relying on the their two way bound model to have been updated.  But due to the sequence of events in Angular they were propagating the old model.  By supplying the latest model as a parameter, we make it easier for consumers to send the correct data.
Adds the latest model as a parameter to the onRefreshRequirements callback of twFieldset
=> Publish model in Fieldset.onRefreshRequirements callback

CHANGELOG.md, package.json, src/forms/upload/multi-upload/multi-upload.spec.js, src/forms/upload/processing-card/processing-card.controller.js, src/forms/upload/services/async-file-saver.service.js, src/forms/upload/upload.spec.js
Uploads from web are failing for live capture photos that are uploaded using `PersistAsync`
https://transferwise.slack.com/archives/C2SGDKP4Y/p1596072668439100
As you can see at [processing-card.controller.js:54](https://github.com/transferwise/styleguide-components/pull/317/files#diff-edaa2d37a284510d3112b18de78ce543R54) we do compute the Base64 data URL of the `Blob` we get, but we are not using it, since the `mitigator-service` works with `MultipartFile`s instead of a `String` on that endpoint which would be risky to change.
Because we append a `Blob` instance to the form data without specifying the `fileName` argument, [it will default to the `blob` string](https://developer.mozilla.org/en-US/docs/Web/API/FormData/append) which is an invalid file name from the `mitigator-service` …
=> [IDWL-] Change upload from live capture to add the file extension if its not exist

CHANGELOG.md, package.json, src/forms/fieldset/fieldset.controller.js, src/forms/fieldset/fieldset.spec.js
Custom validation messages can be set for just particular fields. Previously you need to set it for all of the validations or none
For example if we set: 
```
"validationMessages": {
"pattern": "wrong format"
},
```
Missing validation message for `required` will fallback to default.
Default values combine with custom validation messages
Added this after adding validation messages support to df v2 https://github.com/transferwise/dynamic-interfaces/commit/9963af0a5ce81801d82ccd484ff15ff65a0202cc
=> Allow custom validation messages with defaults as fallback

CHANGELOG.md, package-lock.json, src/forms/upload/camera-capture/camera-capture.controller.js
We want to change the camera context requested by our camera capture component from a square to a 3:4 portrait image.
This is a continuation of https://github.com/transferwise/styleguide-components/pull/298. Japan verification (and now Malaysia verification, and soon enough IDWL verification) has been plagued by this occasional issue where sometimes the image captured by the live camera component is corrupted, and looks like the attached screenshot (I've blurred out the PII, but if I didn't, you'd see that the card details get chopped too, and thus miss out some information)
We don't know the exact root cause for why this happens (and we haven't been able to reproduce it locally). What we do know is:
- when it happens, the pictures are always the exact square dimensions requested …
=> ASIA-3207: Try changing the requested width/height of webcam requests again

CHANGELOG.md, package-lock.json, package.json, src/services/requirements/requirements.service.js, src/services/requirements/requirements.spec.js
The requirements service, which maps V2 dynamic form specifications to V3, was missing support for hidden field types.  This became apparent when we started to remove 'undocumented' fields, as we were removing values from hidden fields.
We were also removing data from select fields, because our 'model cleaning' code expects JSON schema style 'oneOf' selects, not 'values' arrays. 
We now correctly map hidden fields to hidden string schemas.  We now add 'oneOf' arrays next to our 'values' array to enable validation to work correctly
n/a
n/a
n/a
n/a
n/a
=> fix: support V2 hidden fields in requirements service

CHANGELOG.md, package-lock.json, package.json, src/forms/fieldset/fieldset.demo.js, src/forms/fieldset/fieldset.spec.js, src/services/requirements/requirements.service.js, src/services/requirements/requirements.spec.js
Adding prepLegacyValues on checkbox group to map key/name to value/label
=> Fix values fields mapping for checkbox-group component

CHANGELOG.md, package-lock.json, package.json, src/json-schema/validation/valid-model/index.js, src/json-schema/validation/valid-model/spec.js, src/services/requirements/requirements.spec.js
We were encountering a bug in V2 dynamic forms, where an array of enums (visually speaking a list of checkboxes) was being removed from the data model during a refresh.  This was occurring because the code that removed invalid values from models was not correctly implemented for array schemas.
Ensure that invalid array entries are removed from arrays, and valid entries retained.
Fix will also require a bump in verification-components
n/a
n/a
n/a
n/a
=> fix: do not remove array values from models

CHANGELOG.md, package-lock.json, package.json, src/forms/upload/file-input.directive.js
We encountered a situation where the upload component might get stuck, and not process a file upload.  This seemed to occur only when uploading a second file within the same upload component.  Once a subsequent interaction occurs the file begins processing.  This suggests the digest cycle is failing to run in this scenario.
If one is not already running, we manually force a digest cycle after receiving the change event from the underlying file input control.
This PR contains a console.log which is present to help us understand the problem further if the fix does not work.
=> fix: force digest when file input value changes

CHANGELOG.md, package-lock.json, package.json, src/forms/upload/capture-card/capture-card.controller.js, src/forms/upload/capture-card/capture-card.html, src/forms/upload/capture-card/card-capture.spec.js, src/forms/upload/processing-card/index.js, src/forms/upload/services/media-api.service.js
There is a new integration with google where we need to render transferwise.com inside https://microapps.google.com domain. There will be an android native application with a webview which will open transferwise.com inside.
We need to use Media API exposed by microapps for file upload, hence we need to make this the preferred option when the upload component is rendered inside the supported domain.
Use Media API for file upload when the upload component is rendered inside the supported domain.
=> feat: microapps media API support

CHANGELOG.md, package-lock.json, package.json, src/forms/fieldset/fieldset.controller.js, src/forms/fieldset/fieldset.spec.js
Previously the two-way bound isValid property was set using angular's ngForm directive. However, this stopped working when we changed the internal validation to avoid using the ngModel pipeline (which was suppressing invalid values from being broadcast).
We now use the isValidSchema utility to validate the model as it changes
=> fix: Fixes twFieldset form validation

CHANGELOG.md, package-lock.json, package.json, src/forms/fieldset/fieldset.controller.js, src/forms/fieldset/fieldset.spec.js
Previously validity was communicated by the two-way bound isValid component prop. This was being misused by some consumers to attempt to set internal validity. 
We now additionally broadcast validity in the onModelChange callback for a clearer API.
n/a
=> twFieldset now sends validity as a second parameter in onModelChange

CHANGELOG.md, package-lock.json, package.json, src/forms/fieldset/fieldset.controller.js, src/forms/fieldset/fieldset.spec.js, test-utils.js
Previously it did not broadcast a change on load, meaning you had to rely on the two-way bound isValid property for initial validation state.  
Broadcasts a change event on load.  This also fixes a bug where we were not validating required fields.
n/a
n/a
n/a
=> twFieldset now broadcasts an onModelChange with initial model value and validity

CHANGELOG.md, package-lock.json, package.json, src/json-schema/validation/validation-failures/index.js, src/json-schema/validation/validation-failures/spec.js
When applied to strings, minimum and maximum should also be strings, allowing comparison between iso8601 dates.  A numeric minimum/maximum is invalid and should be ignored.
We now ignore numeric minimum/maximum when validating.
n/a
n/a
=> Fix string validation when given incorrect minimum/maximum data type

CHANGELOG.md, package-lock.json, package.json, src/forms/upload/capture-card/capture-card.controller.js, src/forms/upload/capture-card/card-capture.spec.js, src/forms/upload/services/media-api.service.js
We previously checked if microapps is in window and if it isn't we fall back to HTML file input or the camera component.
Spot app does not support html file input and does not throw errors when trying using it.
We will always default to use the Media API when within a spot host url which will then throw an error if microapps is not available in window.
=> Throw an error if we’re in the Spot environment but microapps API is not available

CHANGELOG.md, package-lock.json, package.json, src/forms/currency-input/currency-input.spec.js, src/forms/fieldset/fieldset.component.js, src/forms/fieldset/fieldset.controller.js, src/forms/fieldset/fieldset.spec.js
We recently changed the focus for validity on broadcasting validity alongside the model as the model changes.  However, in the event that the fields change without changing the model (e.g. a refresh requirements call adds a field), then the new validity was not broadcast.
We add an onValidityChange callback that is guaranteed to fire whenever the validity changes.
n/a
n/a
n/a
n/a
=> feat: Fieldset will now broadcast an onValidityChange

CHANGELOG.md, package-lock.json, package.json, src/forms/fieldset/fieldset.component.js, src/forms/fieldset/fieldset.controller.js, src/forms/fieldset/fieldset.spec.js
Required status should come from the fields themselves, not the separate prop. There are no cases in our code base where we depend on this prop, so this should not a breaking change in practice.
Removes the requiredFields prop from Fieldset
=> breaking: remove requiredFields prop from Fieldset

CHANGELOG.md, package-lock.json, package.json, src/forms/field/field.spec.js, src/services/requirements/requirements.service.js
`twField` component incorrectly mapped upper case field type names (`number` vs `NUMBER`) and this resulted in fields having `text` control type - while they should have been something different.
This caused validation issues. Let's take for example field type `NUMBER` - this is the value that's being returned by Dynamic Flows V2 (DF V2) field type value on the network. Example network response for such field:
```
{
'@class': 'ee.tw.dynamic.interfaces.structure.field.NumberField',
key: 'transferId',
name: 'Transfer number',
description: null,
width: 'lg',
type: 'NUMBER',
required: true,
hidden: false,
placeholder: '12345678',
helpText: null,
columns: null,
validationRegexp: '\\d+',
validationMessages: null,
refreshRequirementsOnChange: false,
min: 0,
max: 2147483647,
example: null,
},
``` …
=> fix(Field): handle uppercase field types as well

CHANGELOG.md, package-lock.json, package.json, src/json-schema/array-schema/controller.js, src/json-schema/validation/schema-validators/index.js, src/json-schema/validation/schema-validators/spec.js, src/json-schema/validation/valid-model/index.js, src/json-schema/validation/validation-failures/index.js, src/services/requirements/requirements.service.js, src/utils/index.js, src/utils/string-utils.js
For context, please check #363 
That PR fixed one bug, but it was not fixed all issues with case sensitive field types - this PR fixes all of these issues.
- use `safeToLowerCase` wherever we expect lowercase schema type values
- add test for `isValidSchema` with lowercase and uppercase schema types as well
=> fix(json-schema): handle case sensitive schema types
