transferwise/styleguide-components

- examples/index.html
> Add tw-date in examples

- angular/components/tw-amount-currency-select/tw-amount-currency-select.directive.js
- angular/components/tw-currency-input/tw-currency-input.directive.js
- angular/components/tw-currency-input/tw-currency-input.directive.spec.js
- index.html
- index.js
- partials/tw-amount-currency-select.html
- partials/tw-currency-input.html
Remove symbol from currency input.
Add size support to currency and amount currency.
Update docs.
> Reduce amount currency border to the input-group

- README.md
- package.json
Changes
- bumped the version due to merging the upload directive changes
- added information on releasing a new version
> Bumped the version and added info on releasing to the repo

- demo/css/examples.less
- demo/forms.html
- demo/hack.html
- demo/index.html
- demo/js/index.js
- demo/json/image-upload.json
- demo/partials/forms/checkbox.html
- demo/partials/forms/date-lookup.html
- demo/partials/forms/date.html
- demo/partials/forms/dynamic-control.html
- demo/partials/forms/radio.html
- demo/partials/forms/requirements-form.html
- demo/partials/forms/select.html
- demo/partials/forms/upload.html
- demo/partials/tw-affix.html
- demo/partials/tw-focusable.html
- demo/partials/tw-pop-over.html
- demo/partials/tw-process.html
- demo/partials/tw-tool-tip.html
- demo/partials/tw-validation.html
> Switch tabs to spaces in demo folder

- demo/js/index.js
- demo/partials/tw-process.html
- package.json
> Remove es6 from demo

- CHANGELOG.md
- package-lock.json
- package.json
- src/demo.js
- src/forms/demo.html
- src/forms/demo.js
- src/forms/index.js
- src/forms/radio/radio.demo.html
- src/forms/submit/index.js
- src/forms/submit/submit.component.js
- src/forms/submit/submit.controller.js
- src/forms/submit/submit.demo.html
- src/forms/submit/submit.demo.js
- src/forms/submit/submit.html
- src/forms/submit/submit.spec.js
- src/layout/cards/cards.demo.js
Submit button providing loading indicator and feedback based on successful/failed resolution of a promise.
> Adds a submit button component

- CHANGELOG.md
- demo/json/global-usd-requirements.json
- package.json
- src/forms/fieldset/fieldset.demo.html
- src/forms/fieldset/fieldset.demo.js
- src/forms/fieldset/fieldset.html
- src/forms/requirements-form/requirements-form.controller.js
- src/forms/requirements-form/requirements-form.html
- src/forms/requirements-form/requirements-form.service.js
- src/forms/requirements-form/requirements-form.spec.js
- src/navigation/tabs/tabs.controller.js
- src/services/requirements/requirements.service.js
- src/services/requirements/requirements.spec.js
Backwards compatibility is maintained.
Also fix a tiny type safety issue with tabs.
> Make form use 'properties' internally instead of 'fields'

- CHANGELOG.md
- package-lock.json
- package.json
- src/help/pop-over/pop-over.controller.js
- src/help/pop-over/pop-over.service.js
- src/help/pop-over/pop-over.service.spec.js
Add new logic to the pop over service that will accommodate the new positioning system, which is composed of 4 main positions (top, right, bottom, left) and 3 sub positions (either, left, middle, right or top, middle, bottom). For more details check the Bootstrap [#184](https://github.com/transferwise/bootstrap/pull/184) pull request.
> Add new popover placements to the pop over service

- CHANGELOG.md
- package.json
- src/forms/select/select.controller.js
- src/forms/select/select.html
- src/forms/select/select.spec.js
If more than 12 values are supplied search box will be automatically displayed.
> Automatically show search for long lists of values supplied to twSelect

- CHANGELOG.md
- package-lock.json
- package.json
- src/layout/cards/card.html
- src/layout/cards/cards.spec.js
As part of making activity list cards more visible to customers, we are now adding chevrons to indicate the user that it's a clickable and expandable card item.
> [EXP-XXX] Add chevrons to cards

- CHANGELOG.md
- package-lock.json
- package.json
- src/forms/requirements-form/requirements-form.component.js
- src/forms/requirements-form/requirements-form.controller.js
- src/forms/requirements-form/requirements-form.demo.html
- src/forms/requirements-form/requirements-form.demo.js
- src/forms/requirements-form/requirements-form.html
- src/forms/requirements-form/requirements-form.spec.js
One thing to note, I considered adding it the callback as a '>' rather than '&', as it play better with angular2react, but went with the latter for internal consistency with the other callbacks.  I don't expect this component to be wrapped by React as I'm expecting us to produce a React version before that would be necessary.  '&' also plays a bit nicer for consumers, I discovered some gotchas while experimenting.
> Add callback for model changes on requirements form

- CHANGELOG.md
- package-lock.json
- package.json
- src/services/date/date.service.js
Before if the date was more than 48hours away, then we formatted out the exact time and just displayed the date for medium/short.
With this change we will show the time if the date is within 6days (144 hours).
Was:
Will:
Personally do not see any downsides to that, only being more transparent with time
> Adjust getDateString to get exact time if in 6days

- package.json
- src/layout/cards/card.directive.js
- src/layout/cards/card.html
- src/layout/cards/cards.demo.html
- src/layout/cards/cards.spec.js
- src/services/date/date.service.js
Adds an empty state to the TW Card component, turning off the expand on click behavior.
> Empty card

- .circleci/config.yml
Reverts transferwise/styleguide-components#248
> Revert "Repairing Circle CI builds - Removing Temporarily the Github Release"

- CHANGELOG.md
- README.md
- demo/playground.html
- demo/requirements.html
- package-lock.json
- package.json
- src/json-schema/demo.controller.js
- src/json-schema/demo.js
- src/json-schema/demo.playground.controller.js
- src/json-schema/demo.playground.html
- src/json-schema/object-schema/controller.js
- src/json-schema/object-schema/spec.js
- src/json-schema/one-of-schema/controller.js
- src/json-schema/one-of-schema/spec.js
- src/json-schema/one-of-schema/template.html
- src/json-schema/validation/schema-validators/index.js
- src/json-schema/validation/type-validators/index.js
- src/json-schema/validation/type-validators/spec.js
- src/json-schema/validation/valid-model/index.js
Bug affected schema validations when no ‘required’ array was present.
oneOfSchema component now defaults to the first schema that validates against the model (useful for selecting the correct schema when editing an existing model).
objectSchema component now does not change the input model, only broadcasts via onChange.
New test playground
Also modularises some demo code to separate files.
> Fix couple small JSON schema form bugs, Add demo form testing playground.

- CHANGELOG.md
- package-lock.json
- package.json
- src/forms/upload/camera-capture/camera-capture.controller.js
- src/forms/upload/camera-capture/camera-capture.spec.js
- src/forms/upload/upload.demo.js
Camera direction parameter was not handled correctly causing camera direction to always default to 'environment'
> Camera upload component bugfix

- CHANGELOG.md
- package-lock.json
- package.json
- src/forms/upload/upload.html
Small bug fix, removed elipsis on p tag
> Bug: removed elipsis

- CHANGELOG.md
- package-lock.json
- package.json
- src/forms/field/field.controller.js
- src/forms/form-control/form-control.controller.js
- src/forms/form-control/form-control.spec.js
- src/forms/upload/camera-capture/camera-capture.controller.js
- src/forms/upload/upload.controller.js
I tested latest changes made here against send flow and discovered some problems
There is one console error i have addressed in the PR, also some subtle changes happened to angular digest. 
Added asyncapply around some UI state changes
Fixed a miss routed parameter in callback
> Minor fixes for upload component

- CHANGELOG.md
- package-lock.json
- package.json
- src/forms/upload/camera-capture/camera-capture.controller.js
This change reduces captured image size by 10x
I have checked with verification team and they are fine with image resolution here.
> Use jpeg with compression for camera upload

- CHANGELOG.md
- package-lock.json
- package.json
- src/forms/checkbox-group/checkbox-group.component.js
- src/forms/checkbox-group/checkbox-group.controller.js
- src/forms/checkbox-group/checkbox-group.demo.html
- src/forms/checkbox-group/checkbox-group.demo.js
- src/forms/checkbox-group/checkbox-group.html
- src/forms/checkbox-group/checkbox-group.spec.js
- src/forms/checkbox-group/index.js
- src/forms/demo.html
- src/forms/demo.js
- src/forms/field/field.controller.js
- src/forms/fieldset/fieldset.demo.js
- src/forms/form-control/form-control.demo.js
- src/forms/form-control/form-control.html
- src/forms/form-control/form-control.spec.js
- src/forms/form-control/index.js
- src/forms/index.js
- src/services/requirements/requirements.service.js
As a follow up to this (https://transferwise.atlassian.net/wiki/spaces/DF/pages/1228965495/Multiple-choice+question)
We need to support checkbox groups in DF
Added the component, also mapped to it in form-control
There was no such component
> Add checkbox-group component

- CHANGELOG.md
- package-lock.json
- package.json
- src/forms/checkbox-group/checkbox-group.controller.js
- src/forms/checkbox-group/checkbox-group.spec.js
- src/forms/field/field.controller.js
- src/forms/field/field.html
- src/forms/fieldset/fieldset.controller.js
- src/forms/fieldset/fieldset.demo.js
- src/forms/fieldset/fieldset.html
- src/forms/fieldset/fieldset.spec.js
- src/forms/form-control/form-control.spec.js
- src/services/requirements/requirements.service.js
Moving checkbox-group model conversion into string into fieldSet component as it will only be required for v2
> Make checkbox-group model to be an array

- .circleci/config.yml
> fix code formatting in CircleCI config for beta-release job 

- .eslintignore
- CHANGELOG.md
- package-lock.json
- package.json
Additional newlines in the changelog were breaking the release build
Fixes the format of the changelog
n/a
n/a
n/a
n/a
n/a
> fix release build by fixing changelog format

- CHANGELOG.md
- package-lock.json
- package.json
> update version and fix changelog file

- .circleci/config.yml
- .eslintignore
- CHANGELOG.md
- package-lock.json
- package.json
- src/forms/fieldset/fieldset.controller.js
- src/forms/fieldset/fieldset.spec.js
- src/forms/upload/camera-capture/camera-capture.controller.js
- src/forms/upload/multi-upload/multi-upload.spec.js
- src/forms/upload/processing-card/processing-card.controller.js
- src/forms/upload/services/async-file-saver.service.js
- src/forms/upload/upload.spec.js
- src/layout/cards/card.html
- src/services/requirements/requirements.service.js
- src/services/requirements/requirements.spec.js
- webpack.config.dev.js
- webpack.config.js
> Exclude angular icons from package bundle

- CHANGELOG.md
- package-lock.json
- package.json
- webpack.config.js
> exclude icons bundle from final package bundle

- CHANGELOG.md
- package-lock.json
- package.json
- src/demo.js
- src/index.js
> change the way we add icons to demo

- .circleci/config.yml
Circle configuration references an unknown context
Change the circle context's to match those used in Neptune
> fix: change circle contexts

- .circleci/config.yml
Attempt to see if this fixes release job permissions error
Revert to using previous circle user
> Revert circle user

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/forms/upload/camera-capture/camera-capture.html
- src/forms/upload/camera-capture/camera-capture.less
2 problems here
1. TW icon does not scale to button size the way glyphicon does making it off center and ugly
2. "Tick" icon does not exist
Which makes our camera upload component look like this
Fix the button problems. It seems our icon assets are not made to scale nicely. I understand there is another way to do it with svg viewbox attribute, but that solution wont wont apply here. 
Updated spec is to use a 56px button with a 24px icon as advised by design team.
> Fix icon problems related to live upload component

- CHANGELOG.md
- package-lock.json
- package.json
- src/forms/upload/upload.controller.js
The camera only feature of the upload component was not blocking customers to use the drag and drop behavior, so this PR is fixing it.
https://transferwise.atlassian.net/browse/VUX-547
> VUX-547 - Disable drag and drop on non eligible cases

- .circleci/config.yml
- package.json
Slow CI builds, and occasional failures due to OOM.
- splitted `test` job onto three separate jobs `install`, `lint` and `test` where each performs its own single task, `test` and `lint` now run simultaneously
- applied `--maxWorkers=4` for Jest test runner
Before             |  After
:-------------------------:|:-------------------------:
> CI build improvements

- .circleci/config.yml
- package.json
Forget todo that in previous PR https://github.com/transferwise/styleguide-components/pull/353
Make `release` job depend on `lint` one during build on `master` branch.
See example of such CI workflow https://app.circleci.com/pipelines/github/transferwise/styleguide-components/138/workflows/a785c9d0-31de-4f62-9c60-d370c7b1e767
> Ci improvements
